version: '3.9'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_project
    restart: always
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - PYTHONUNBUFFERED=1
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ORACLE_HOST=${ORACLE_HOST}
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - SQLITE_DATABASE=${SQLITE_DATABASE}
      - SQLITE_PATH=${SQLITE_PATH}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./sqlite_db:/opt/airflow/sqlite_db
      - ./config.py:/opt/airflow/config.py
      - ./requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      - mssql
      - mysql
      - oracle
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    restart: always
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle_db
    restart: always
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "${ORACLE_PORT}:1521"
    networks:
      - backend
  
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
